name: rsg
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.9.0
  - numpy
  - pandas
  - matplotlib
  - pytorch=1.11.0
  - scipy=1.5.2
  - tqdm
  - hydra-core
  - pyyaml
  - jupyter
  - pathlib
  - seaborn
  - mlflow
  - pip: 
    - yfinance