name: rsg
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python>=3.11.0
  - numpy
  - pandas
  - matplotlib
  - pytorch
  - scipy
  - tqdm
  - pip
  - hydra-core
  - pyyaml
  - jupyter
  - pre-commit
  - pathlib
  - seaborn
  - black
  - isort
  - loguru
  - mlflow=3.8.0
  - pip: 
    - yfinance